const code1 = 'DLRURUDLULRDRUDDRLUUUDLDLDLRLRRDRRRLLLLLDDRRRDRRDRRRLRRURLRDUULRLRRDDLULRLLDUDLULURRLRLDUDLURURLDRDDULDRDRDLDLLULULLDDLRRUDULLUULRRLLLURDRLDDLDDLDRLRRLLRURRUURRRRLUDLRDDDDRDULRLLDDUURDUDRLUDULLUDLUDURRDRDUUUUDDUDLLLRLUULRUURDLRLLRRLRLLDLLRLLRRRURLRRLURRLDLLLUUDURUDDLLUURRDRDRRDLLDDLLRDRDRRLURLDLDRDLURLDULDRURRRUDLLULDUDRURULDUDLULULRRRUDLUURRDURRURRLRRLLRDDUUUUUDUULDRLDLLRRUDRRDULLLDUDDUDUURLRDLULUUDLDRDUUUDDDUDLDURRULUULUUULDRUDDLLLDLULLRLRLUDULLDLLRLDLDDDUUDURDDDLURDRRDDLDRLLRLRR'
const code2 = 'RLDUDURDRLLLLDDRRRURLLLRUUDDLRDRDDDUDLLUDDLRDURLDRDLLDRULDDRLDDDRLDRDDDRLLULDURRRLULDRLRDRDURURRDUDRURLDRLURDRLUULLULLDLUDUDRDRDDLDDDDRDURDLUDRDRURUDDLLLRLDDRURLLUDULULDDLLLDLUDLDULUUDLRLURLDRLURURRDUUDLRDDDDDRLDULUDLDDURDLURLUURDLURLDRURRLDLLRRUDRUULLRLDUUDURRLDURRLRUULDDLDLDUUDDRLDLLRRRUURLLUURURRURRLLLUDLDRRDLUULULUDDULLUDRLDDRURDRDUDULUDRLRRRUULLDRDRLULLLDURURURLURDLRRLLLDRLDUDLLLLDUUURULDDLDLLRRUDDDURULRLLUDLRDLUUDDRDDLLLRLUURLDLRUURDURDDDLLLLLULRRRURRDLUDLUURRDRLRUDUUUURRURLRDRRLRDRDULLDRDRLDURDDUURLRUDDDDDLRLLRUDDDDDURURRLDRRUUUDLURUUDRRDLLULDRRLRRRLUUUD';
const code3 = 'RDRURLLUUDURURDUUULLRDRLRRLRUDDUDRURLLDLUUDLRLLDDURRURLUDUDDURLURLRRURLLURRUDRUDLDRLLURLRUUURRUDDDURRRLULLLLURDLRLLDDRLDRLLRRDLURDLRDLDUDRUULLDUUUDLURRLLRUDDDUUURLURUUDRLRULUURLLRLUDDLLDURULLLDURDLULDLDDUDULUDDULLRDRURDRRLLDLDDDDRUDLDRRLLLRLLLRRULDLRLRLRLLDLRDRDLLUDRDRULDUURRDDDRLLRLDLDRDUDRULUDRDLDLDDLLRULURLLURDLRRDUDLULLDLULLUDRRDDRLRURRLDUDLRRUUDLDRLRLDRLRRDURRDRRDDULURUUDDUUULRLDRLLDURRDLUULLUDRDDDLRUDLRULLDDDLURLURLRDRLLURRRUDLRRLURDUUDRLRUUDUULLRUUUDUUDDUURULDLDLURLRURLRUDLULLULRULDRDRLLLRRDLU';
const code4 = 'RRRRDRLUUULLLRLDDLULRUUURRDRDRURRUURUDUULRULULRDRLRRLURDRRRULUUULRRUUULULRDDLLUURRLLDUDRLRRLDDLDLLDURLLUDLDDRRURLDLULRDUULDRLRDLLDLRULLRULLUDUDUDDUULDLUUDDLUDDUULLLLLURRDRULURDUUUDULRUDLLRUUULLUULLLRUUDDRRLRDUDDRULRDLDLLLLRLDDRRRULULLLDLRLURRDULRDRDUDDRLRLDRRDLRRRLLDLLDULLUDDUDDRULLLUDDRLLRRRLDRRURUUURRDLDLURRDLURULULRDUURLLULDULDUDLLULDDUURRRLDURDLUDURLDDRDUDDLLUULDRRLDLLUDRDURLLDRLDDUDURDLUUUUURRUULULLURLDUUULLRURLLLUURDULLUULDRULLUULRDRUULLRUDLDDLRLURRUUDRLRRRULRUUULRULRRLDLUDRRLL';
const code5 = 'ULRLDLLURDRRUULRDUDDURDDDLRRRURLDRUDDLUDDDLLLRDLRLLRRUUDRRDRUULLLULULUUDRRRDRDRUUUUULRURUULULLULDULURRLURUDRDRUDRURURUDLDURUDUDDDRLRLLLLURULUDLRLDDLRUDDUUDURUULRLLLDDLLLLRRRDDLRLUDDUULRRLLRDUDLLDLRRUUULRLRDLRDUDLLLDLRULDRURDLLULLLRRRURDLLUURUDDURLDUUDLLDDRUUDULDRDRDRDDUDURLRRRRUDURLRRUDUDUURDRDULRLRLLRLUDLURUDRUDLULLULRLLULRUDDURUURDLRUULDURDRRRLLLLLUUUULUULDLDULLRURLUDLDRLRLRLRDLDRUDULDDRRDURDDULRULDRLRULDRLDLLUDLDRLRLRUDRDDR';

const keyMap = {
  1: {
    U: 1,
    L: 1,
    R: 1,
    D: 3,
  },
  2: {
    U: 2,
    L: 2,
    R: 3,
    D: 6,
  },
  3: {
    U: 1,
    L: 2,
    R: 4,
    D: 7,
  },
  4: {
    U: 4,
    L: 3,
    R: 4,
    D: 8,
  },
  5: {
    U: 5,
    L: 5,
    R: 6,
    D: 5,
  },
  6: {
    U: 2,
    L: 5,
    R: 7,
    D: 'A',
  },
  7: {
    U: 3,
    L: 6,
    R: 8,
    D: 'B',
  },
  8: {
    U: 4,
    L: 7,
    R: 9,
    D: 'C',
  },
  9: {
    U: 9,
    L: 8,
    R: 9,
    D: 9,
  },
  A: {
    U: 6,
    L: 'A',
    R: 'B',
    D: 'A',
  },
  B: {
    U: 7,
    L: 'A',
    R: 'C',
    D: 'D',
  },
  C: {
    U: 8,
    L: 'B',
    R: 'C',
    D: 'C',
  },
  D: {
    U: 'B',
    L: 'D',
    R: 'D',
    D: 'D',
  },
};

const findKey = (code, start) => {
  let current = start;
  const codeArr = code.split('');
  codeArr.forEach(letter => {
    current = keyMap[current][letter];
  });
  console.log('Current Key:', current);
};

findKey(code1, 5);
findKey(code2, 'D');
findKey(code3, 8);
findKey(code4, 7);
findKey(code5, 'A');

// const findButton = (code, x, y) => {
//   const codeArr = code.split('');
//   let currentX = x;
//   let currentY = y;
//   codeArr.forEach(letter => {
//     if (letter === 'U') {
//       currentY = currentY === 0 ? 0 : currentY - 1;
//     } else if (letter === 'D') {
//       currentY = currentY === 2 ? 2 : currentY + 1;
//     } else if (letter === 'L') {
//       currentX = currentX === 0 ? 0 : currentX - 1;
//     } else if (letter === 'R') {
//       currentX = currentX === 2 ? 2 : currentX + 1;
//     }
//   });
//   console.log('X:', currentX, 'Y:', currentY);
// };

// console.log('My code:');
// findButton(code1, 1, 1);
// findButton(code2, 2, 2);
// findButton(code3, 1, 1);
// findButton(code4, 1, 1);
// findButton(code5, 0, 1);
